# ============================================================
# ALEX STREAMING — V16
# Edita este archivo para cambiar productos, precios y datos.
# ============================================================

STORE = {'name': 'ALEX STREAMING',
 'domain': 'https://alex-streaming.onrender.com',
 'whatsapp': '51984933571',
 'currency': 'S/',
 'support_text': 'Atención directa por WhatsApp',
 'status_text': 'ALEX STREAMING // PREMIUM ACCESS ONLINE',
 'edition_text': 'PREMIUM ACCESS',
 'entry_tagline': 'STREAMING • IA • SOFTWARE • REDES • LIVE'}

# Catálogo principal. Los planes con price=None muestran “Consultar”.
PRODUCTS = [{'id': 'max',
  'name': 'HBO Max',
  'icon': 'simple-icons:hbomax',
  'accent': '#8A5CFF',
  'category': 'Streaming',
  'badge': 'MAX',
  'description': 'Series, películas y entretenimiento premium.',
  'plans': [{'name': 'Estándar · 1 mes', 'price': 5},
            {'name': 'Estándar · 3 meses', 'price': 15},
            {'name': 'Platino · 1 mes', 'price': 8},
            {'name': 'Cuenta completa Estándar · 3 meses', 'price': 15}],
  'details': ['Incluye planes Estándar, Platino y cuenta completa según disponibilidad.',
              'Elige la duración y modalidad de acceso antes de confirmar tu pedido.',
              'Entrega y activación coordinadas directamente por WhatsApp.'],
  'notes': [],
  'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/7/7e/HBO_Max_May_2025_%28Horizontal%29.svg',
  'logo_class': 'brand-logo brand-logo-wide brand-logo-whiteplate',
  'display_name': 'HBO Max'},
 {'id': 'disney',
  'name': 'Disney+',
  'icon': 'simple-icons:disneyplus',
  'accent': '#63A7FF',
  'category': 'Streaming',
  'badge': 'DISNEY',
  'description': 'Disney, Pixar, Marvel, Star Wars y más.',
  'plans': [{'name': 'Cuenta completa', 'price': 15},
            {'name': 'Perfil Premium', 'price': 12},
            {'name': 'Disney+ + Hulu + Star', 'price': 16}],
  'details': ['Disponible en cuenta completa, perfil premium y combo Disney+ + Hulu + Star.',
              'Puedes solicitar bot/código de activación si aplica al tipo de entrega coordinada.',
              'Ideal para películas, series y contenido familiar.'],
  'notes': [],
  'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/6/64/Disney%2B_2024.svg',
  'logo_class': 'brand-logo brand-logo-wide brand-logo-whiteplate',
  'display_name': 'Disney+'},
 {'id': 'appletv',
  'name': 'Apple TV+',
  'icon': 'simple-icons:appletv',
  'accent': '#F5F5F7',
  'category': 'Streaming',
  'badge': 'APPLE',
  'description': 'Producciones originales y estrenos seleccionados.',
  'plans': [{'name': 'Cuenta completa', 'price': 12}, {'name': 'Perfil', 'price': 5}],
  'details': ['Disponible en cuenta completa o perfil individual.',
              'Compatible con dispositivos admitidos por Apple TV+.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/appletv/FFFFFF',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Apple TV+'},
 {'id': 'primevideo',
  'name': 'Prime Video',
  'icon': 'simple-icons:primevideo',
  'accent': '#00A8E1',
  'category': 'Streaming',
  'badge': 'PRIME',
  'description': 'Películas, series y contenido original.',
  'plans': [{'name': 'Cuenta completa · 1 mes', 'price': 15},
            {'name': 'Perfil para TV · 30 días', 'price': 5},
            {'name': 'Cuenta completa · 3 meses', 'price': 20},
            {'name': 'Perfil · 3 meses · cualquier dispositivo', 'price': 12}],
  'details': ['Cuenta completa y perfiles para distintos periodos según el plan.',
              'Si el acceso es solo para Prime Video, evita realizar compras o alquileres dentro de Amazon.',
              'Algunas activaciones pueden ser solo para TV o para cualquier dispositivo, según el producto elegido.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/primevideo/00A8E1',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Prime Video'},
 {'id': 'paramount',
  'name': 'Paramount+',
  'icon': 'simple-icons:paramountplus',
  'accent': '#1B67FF',
  'category': 'Streaming',
  'badge': 'PLUS',
  'description': 'Películas, series y entretenimiento familiar.',
  'plans': [{'name': 'Perfil exclusivo · 1 mes', 'price': 10}, {'name': 'Cuenta completa', 'price': 25}],
  'details': ['Perfil exclusivo y cuenta completa disponibles.',
              'Ideal para películas, series y eventos especiales según el catálogo activo.',
              'No cambiar datos de la cuenta si eso invalida la garantía ofrecida.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/paramountplus/0064FF',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Paramount+'},
 {'id': 'crunchyroll',
  'name': 'Crunchyroll',
  'icon': 'simple-icons:crunchyroll',
  'accent': '#F47521',
  'category': 'Streaming',
  'badge': 'ANIME',
  'description': 'Anime, simulcasts y estrenos.',
  'plans': [{'name': 'Cuenta completa · 1 mes', 'price': 12}, {'name': 'Cuenta completa · 3 meses', 'price': 25}],
  'details': ['Cuenta completa con hasta 5 perfiles disponibles según el plan.',
              'En algunos planes tú mismo administras los perfiles y usuarios.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/crunchyroll/F47521',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Crunchyroll'},
 {'id': 'dgo',
  'name': 'DGO',
  'icon': 'simple-icons:directv',
  'accent': '#00AEEF',
  'category': 'Streaming',
  'badge': 'TV LIVE',
  'description': 'TV en vivo, series, películas y planes deportivos según disponibilidad.',
  'plans': [{'name': 'DGO + Liga 1 Max · perfil / TV', 'price': 18},
            {'name': 'DGO Oro · cuenta completa sin Liga', 'price': 25},
            {'name': 'DGO Bronce · perfil', 'price': 15},
            {'name': 'DGO Oro + Liga 1 Max · cuenta completa', 'price': 35},
            {'name': 'DGO Bronce · cuenta completa', 'price': 25}],
  'details': ['Combina TV en vivo, canales deportivos, series y películas según el plan.',
              'Algunas versiones con Liga 1 Max son solo para TV y pueden requerir activación a pedido.',
              'Los beneficios y cantidad de canales pueden variar según el plan contratado.'],
  'notes': [],
  'logo_url': 'https://commons.wikimedia.org/wiki/Special:Redirect/file/DGO-logo.svg',
  'logo_class': 'brand-logo brand-logo-wide brand-logo-whiteplate',
  'display_name': 'DGO'},
 {'id': 'viki',
  'name': 'Viki Rakuten',
  'icon': 'simple-icons:rakuten',
  'accent': '#BF0000',
  'category': 'Streaming',
  'badge': 'K-DRAMA',
  'description': 'Dramas asiáticos, películas y contenido internacional.',
  'plans': [{'name': 'Perfil', 'price': 8}],
  'details': ['Acceso a dramas asiáticos, K-Dramas, J-Dramas, C-Dramas, películas y contenido internacional.',
              'Contenido con subtítulos en distintos idiomas según disponibilidad de Viki.'],
  'notes': [],
  'logo_url': 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rakuten_Viki_logo.svg',
  'logo_class': 'brand-logo brand-logo-wide brand-logo-whiteplate',
  'display_name': 'Rakuten Viki'},
 {'id': 'vix',
  'name': 'ViX Premium',
  'icon': 'simple-icons:vix',
  'accent': '#FF6B00',
  'category': 'Streaming',
  'badge': 'VIX',
  'description': 'Series, películas y entretenimiento en español.',
  'plans': [{'name': 'Cuenta completa', 'price': 10}, {'name': 'Perfil · 1 mes', 'price': 5}],
  'details': ['Cuenta completa: se entrega el acceso acordado para ViX Premium.',
              'Perfil de 1 mes: uso en el dispositivo acordado y respetando la asignación del perfil.'],
  'notes': [],
  'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/6/6a/ViX_Logo.svg',
  'logo_class': 'brand-logo brand-logo-wide brand-logo-whiteplate',
  'display_name': 'ViX'},
 {'id': 'movistar',
  'name': 'Movistar Play',
  'icon': 'simple-icons:movistar',
  'accent': '#019DF4',
  'category': 'Streaming',
  'badge': 'MOVISTAR',
  'description': 'Entretenimiento y contenido de Movistar Play.',
  'plans': [{'name': 'Perfil', 'price': 15}, {'name': 'Cuenta completa', 'price': 25}],
  'details': ['Disponible en modalidad perfil o cuenta completa según el plan seleccionado.',
              'Entrega y condiciones coordinadas por WhatsApp.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/movistar/019DF4',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Movistar'},
 {'id': 'netflix',
  'name': 'Netflix',
  'icon': 'simple-icons:netflix',
  'accent': '#E50914',
  'category': 'Streaming',
  'badge': 'NETFLIX',
  'description': 'Accesos y activaciones coordinadas para Netflix.',
  'plans': [{'name': 'Activación TV · 30 días · acceso autorizado', 'price': 6},
            {'name': 'Premium · activación a TV', 'price': 15},
            {'name': 'Cuenta completa · 1 mes', 'price': 48}],
  'details': ['Activación para TV por 30 días disponible cuando el acceso sea legítimo y autorizado.',
              'También disponible Premium para TV y cuenta completa por 1 mes según el plan elegido.',
              'La activación y entrega se coordinan por WhatsApp.'],
  'notes': ['No incluye acceso a cuentas ajenas, credenciales obtenidas sin permiso ni métodos tipo “hit”.'],
  'logo_url': 'https://cdn.simpleicons.org/netflix/E50914',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Netflix'},
 {'id': 'youtubepremium',
  'name': 'YouTube Premium',
  'icon': 'simple-icons:youtube',
  'accent': '#FF0000',
  'category': 'Streaming',
  'badge': 'YOUTUBE',
  'description': 'YouTube Premium con activación coordinada para TV.',
  'plans': [{'name': 'Activación a TV · 30 días', 'price': 7}],
  'details': ['Activación para TV por 30 días.',
              'Entrega y activación coordinadas directamente por WhatsApp.',
              'Usa únicamente accesos y activaciones autorizadas.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/youtube/FF0000',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'YouTube Premium'},
 {'id': 'peacock',
  'name': 'Peacock',
  'icon': 'simple-icons:peacock',
  'accent': '#F5C518',
  'category': 'Streaming',
  'badge': 'PEACOCK',
  'description': 'Series, películas, deportes y entretenimiento de Peacock.',
  'plans': [{'name': 'Plan disponible', 'price': None}],
  'details': ['Consulta disponibilidad, modalidad y duración por WhatsApp.'],
  'notes': [],
  'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/2/20/NBCUniversal_Peacock_Logo_%282026%29.svg',
  'logo_class': 'brand-logo brand-logo-wide brand-logo-whiteplate',
  'display_name': 'Peacock'},
 {'id': 'mubi',
  'name': 'MUBI',
  'icon': 'simple-icons:mubi',
  'accent': '#FFFFFF',
  'category': 'Streaming',
  'badge': 'CINEMA',
  'description': 'Cine seleccionado, clásicos, estrenos y películas de autor.',
  'plans': [{'name': 'Plan disponible', 'price': None}],
  'details': ['Consulta disponibilidad y duración antes de comprar.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/mubi/FFFFFF',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'MUBI'},
 {'id': 'plutotv',
  'name': 'Pluto TV',
  'icon': 'simple-icons:plutotv',
  'accent': '#FFD300',
  'category': 'Streaming',
  'badge': 'LIVE TV',
  'description': 'Canales en vivo y contenido bajo demanda.',
  'plans': [{'name': 'Servicio / soporte', 'price': None}],
  'details': ['Consulta las opciones disponibles para tu dispositivo.'],
  'notes': [],
  'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Pluto_TV_logo.svg',
  'logo_class': 'brand-logo brand-logo-wide brand-logo-whiteplate',
  'display_name': 'Pluto TV'},
 {'id': 'plex',
  'name': 'Plex',
  'icon': 'simple-icons:plex',
  'accent': '#E5A00D',
  'category': 'Streaming',
  'badge': 'PLEX',
  'description': 'Biblioteca multimedia, streaming y reproducción multidispositivo.',
  'plans': [{'name': 'Plan disponible', 'price': None}],
  'details': ['Consulta disponibilidad y modalidad por WhatsApp.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/plex/E5A00D',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Plex'},
 {'id': 'spotify',
  'name': 'Spotify Premium',
  'icon': 'simple-icons:spotify',
  'accent': '#1ED760',
  'category': 'Streaming',
  'badge': 'MUSIC',
  'description': 'Música, playlists y audio premium.',
  'plans': [{'name': '1 mes · correo y contraseña', 'price': 10}, {'name': 'Activación a correo propio', 'price': 8}],
  'details': ['Plan de 1 mes con correo y contraseña según el tipo de entrega.',
              'También disponible activación a correo propio.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/spotify/1ED760',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Spotify'},
 {'id': 'surfshark',
  'name': 'Surfshark VPN',
  'icon': 'simple-icons:surfshark',
  'accent': '#178BF4',
  'category': 'VPN',
  'badge': 'VPN',
  'description': 'VPN para privacidad y conexión segura.',
  'plans': [{'name': '3 meses', 'price': 15}, {'name': 'Activación por código · 30 días', 'price': 8}],
  'details': ['Plan de 3 meses y activación mediante código por 30 días según disponibilidad.',
              'Activación y soporte coordinados por WhatsApp.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/surfshark/178BF1',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Surfshark'},
 {'id': 'combo-disney-max',
  'name': 'Disney+ + HBO Max',
  'icon': 'lucide:package-plus',
  'accent': '#9c71ff',
  'category': 'Combos',
  'badge': 'DUO',
  'description': 'Combo de entretenimiento por perfil.',
  'plans': [{'name': 'Perfil · combo', 'price': 13}],
  'details': ['Incluye Disney+, HBO Max en un solo combo.',
              'La modalidad exacta de perfil/cuenta y la duración dependen del plan seleccionado.'],
  'notes': [],
  'combo_logos': [{'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/6/64/Disney%2B_2024.svg',
                   'logo_class': 'brand-logo',
                   'name': 'Disney+',
                   'icon': 'simple-icons:disneyplus'},
                  {'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/7/7e/HBO_Max_May_2025_%28Horizontal%29.svg',
                   'logo_class': 'brand-logo',
                   'name': 'HBO Max',
                   'icon': 'simple-icons:hbomax'}]},
 {'id': 'combo-hbo-prime',
  'name': 'HBO Max + Prime Video',
  'icon': 'lucide:package-plus',
  'accent': '#6C7DFF',
  'category': 'Combos',
  'badge': 'DUO',
  'description': 'Combo de HBO Max y Prime Video.',
  'plans': [{'name': 'Perfil · combo', 'price': 12}],
  'details': ['Incluye HBO Max, Prime Video en un solo combo.',
              'La modalidad exacta de perfil/cuenta y la duración dependen del plan seleccionado.'],
  'notes': [],
  'combo_logos': [{'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/7/7e/HBO_Max_May_2025_%28Horizontal%29.svg',
                   'logo_class': 'brand-logo',
                   'name': 'HBO Max',
                   'icon': 'simple-icons:hbomax'},
                  {'logo_url': 'https://cdn.simpleicons.org/primevideo/00A8E1',
                   'logo_class': 'brand-logo',
                   'name': 'Prime Video',
                   'icon': 'simple-icons:primevideo'}]},
 {'id': 'combo-netflix-disney-prime',
  'name': 'Netflix + Disney+ + Prime Video',
  'icon': 'lucide:boxes',
  'accent': '#ff5858',
  'category': 'Combos',
  'badge': 'TRIO',
  'description': 'Tres perfiles de entretenimiento por 1 mes.',
  'plans': [{'name': 'Perfiles · 1 mes', 'price': 20}],
  'details': ['Incluye Netflix, Disney+, Prime Video en un solo combo.',
              'La modalidad exacta de perfil/cuenta y la duración dependen del plan seleccionado.'],
  'notes': [],
  'combo_logos': [{'logo_url': 'https://cdn.simpleicons.org/netflix/E50914',
                   'logo_class': 'brand-logo',
                   'name': 'Netflix',
                   'icon': 'simple-icons:netflix'},
                  {'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/6/64/Disney%2B_2024.svg',
                   'logo_class': 'brand-logo',
                   'name': 'Disney+',
                   'icon': 'simple-icons:disneyplus'},
                  {'logo_url': 'https://cdn.simpleicons.org/primevideo/00A8E1',
                   'logo_class': 'brand-logo',
                   'name': 'Prime Video',
                   'icon': 'simple-icons:primevideo'}]},
 {'id': 'combo-paramount-disney-prime',
  'name': 'Paramount+ + Disney+ + Prime Video',
  'icon': 'lucide:boxes',
  'accent': '#3f8dff',
  'category': 'Combos',
  'badge': 'TRIO',
  'description': 'Combo de tres servicios de streaming.',
  'plans': [{'name': 'Perfiles · 1 mes', 'price': 25}],
  'details': ['Incluye Paramount+, Disney+, Prime Video en un solo combo.',
              'La modalidad exacta de perfil/cuenta y la duración dependen del plan seleccionado.'],
  'notes': [],
  'combo_logos': [{'logo_url': 'https://cdn.simpleicons.org/paramountplus/0064FF',
                   'logo_class': 'brand-logo',
                   'name': 'Paramount+',
                   'icon': 'simple-icons:paramountplus'},
                  {'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/6/64/Disney%2B_2024.svg',
                   'logo_class': 'brand-logo',
                   'name': 'Disney+',
                   'icon': 'simple-icons:disneyplus'},
                  {'logo_url': 'https://cdn.simpleicons.org/primevideo/00A8E1',
                   'logo_class': 'brand-logo',
                   'name': 'Prime Video',
                   'icon': 'simple-icons:primevideo'}]},
 {'id': 'combo-disney-prime',
  'name': 'Disney+ + Prime Video',
  'icon': 'lucide:package',
  'accent': '#3fb5ff',
  'category': 'Combos',
  'badge': 'DUO',
  'description': 'Combo de dos perfiles de entretenimiento.',
  'plans': [{'name': 'Perfiles · 1 mes', 'price': 15}],
  'details': ['Incluye Disney+, Prime Video en un solo combo.',
              'La modalidad exacta de perfil/cuenta y la duración dependen del plan seleccionado.'],
  'notes': [],
  'combo_logos': [{'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/6/64/Disney%2B_2024.svg',
                   'logo_class': 'brand-logo',
                   'name': 'Disney+',
                   'icon': 'simple-icons:disneyplus'},
                  {'logo_url': 'https://cdn.simpleicons.org/primevideo/00A8E1',
                   'logo_class': 'brand-logo',
                   'name': 'Prime Video',
                   'icon': 'simple-icons:primevideo'}]},
 {'id': 'combo-prime-paramount',
  'name': 'Prime Video + Paramount+',
  'icon': 'lucide:package',
  'accent': '#3B9AFF',
  'category': 'Combos',
  'badge': 'DUO',
  'description': 'Combo de Prime Video y Paramount+.',
  'plans': [{'name': 'Perfil · combo', 'price': 18}],
  'details': ['Incluye Prime Video, Paramount+ en un solo combo.',
              'La modalidad exacta de perfil/cuenta y la duración dependen del plan seleccionado.'],
  'notes': [],
  'combo_logos': [{'logo_url': 'https://cdn.simpleicons.org/primevideo/00A8E1',
                   'logo_class': 'brand-logo',
                   'name': 'Prime Video',
                   'icon': 'simple-icons:primevideo'},
                  {'logo_url': 'https://cdn.simpleicons.org/paramountplus/0064FF',
                   'logo_class': 'brand-logo',
                   'name': 'Paramount+',
                   'icon': 'simple-icons:paramountplus'}]},
 {'id': 'combo-chatgpt-canva',
  'name': 'ChatGPT + Canva',
  'icon': 'lucide:sparkles',
  'accent': '#10E9B3',
  'category': 'Combos',
  'badge': 'AI DUO',
  'description': 'Combo de herramientas de IA y diseño. Solo para activaciones y accesos autorizados.',
  'plans': [{'name': '1 mes', 'price': 15}, {'name': '3 meses', 'price': 40}],
  'details': [],
  'notes': [],
  'combo_logos': [{'logo_url': 'https://cdn.simpleicons.org/openai/FFFFFF',
                   'logo_class': 'brand-logo',
                   'name': 'ChatGPT',
                   'icon': 'simple-icons:openai'},
                  {'logo_url': 'https://cdn.simpleicons.org/canva/00C4CC',
                   'logo_class': 'brand-logo',
                   'name': 'Canva',
                   'icon': 'simple-icons:canva'}]},
 {'id': 'combo-google-canva',
  'name': 'Google + Canva',
  'icon': 'lucide:cloud-cog',
  'accent': '#65A5FF',
  'category': 'Combos',
  'badge': 'WORK',
  'description': 'Combo de herramientas Google y Canva.',
  'plans': [{'name': '3 meses', 'price': 12}],
  'details': [],
  'notes': [],
  'combo_logos': [{'logo_url': 'https://cdn.simpleicons.org/google/FFFFFF',
                   'logo_class': 'brand-logo',
                   'name': 'Google',
                   'icon': 'simple-icons:google'},
                  {'logo_url': 'https://cdn.simpleicons.org/canva/00C4CC',
                   'logo_class': 'brand-logo',
                   'name': 'Canva',
                   'icon': 'simple-icons:canva'}]},
 {'id': 'duolingo',
  'name': 'Duolingo',
  'icon': 'simple-icons:duolingo',
  'accent': '#58CC02',
  'category': 'Educación',
  'badge': 'LEARN',
  'description': 'Cuenta privada y de uso personal durante 30 días.',
  'plans': [{'name': '30 días', 'price': None}],
  'details': ['No editar el método de pago.',
              'No compartir credenciales con terceros.',
              'Una vez cambiado el correo, la cuenta queda bajo tu control.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/duolingo/58CC02',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Duolingo'},
 {'id': 'elevenlabs',
  'name': 'ElevenLabs Creator',
  'icon': 'simple-icons:elevenlabs',
  'accent': '#FFFFFF',
  'category': 'IA y productividad',
  'badge': '121K',
  'description': 'Cuenta Creator con 121,000 créditos para generación y clonación de voz profesional.',
  'plans': [{'name': 'Creator · 25 a 30 días', 'price': None}],
  'details': ['121,000 créditos incluidos.',
              'Clonación de voz profesional y audio de hasta 192 kbps.',
              'Hasta 1,000 proyectos de estudio.',
              'Cuenta compartida con una persona más.',
              'Garantía de 25 días por fallas ajenas al usuario.'],
  'notes': ['No cambiar facturación, correo, contraseña ni datos de la cuenta.'],
  'logo_url': 'https://cdn.simpleicons.org/elevenlabs/FFFFFF',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'ElevenLabs'},
 {'id': 'gamma-pro',
  'name': 'Gamma Pro AI',
  'icon': 'lucide:presentation',
  'accent': '#8B5CF6',
  'category': 'IA y productividad',
  'badge': 'GAMMA',
  'description': 'Gamma Pro para crear presentaciones, documentos y páginas con IA.',
  'plans': [{'name': 'Cuenta completa · 1 mes · 4,000 créditos IA', 'price': None},
            {'name': 'Gamma · 1 mes', 'price': 15}],
  'details': ['Gamma Pro completo por 1 mes con 4,000 créditos de IA para funciones avanzadas.',
              'Ideal para crear presentaciones, documentos y páginas con resultados premium.',
              'Se entrega correo y clave en el plan personal/privado.',
              'Entrega rápida y soporte 24/7 coordinado por WhatsApp.'],
  'notes': []},
 {'id': 'google-storage',
  'name': 'Google One + Gemini',
  'icon': 'simple-icons:google',
  'accent': '#4285F4',
  'category': 'IA y productividad',
  'badge': '2TB',
  'description': 'Almacenamiento ampliado de Google con beneficios de IA según el plan.',
  'plans': [{'name': 'Perfil · 3 meses · 2TB + Gemini', 'price': 15},
            {'name': 'Perfil · 6 meses · 2TB + Gemini', 'price': 25},
            {'name': 'Cuenta completa · 18 meses', 'price': 50},
            {'name': 'Gemini · activación a correo · 18 meses', 'price': 15}],
  'details': ['Planes familiares con 2TB de almacenamiento y beneficios Google One.',
              'Incluye Gemini 2.5 Pro según el plan indicado.',
              'La expansión de almacenamiento funciona para correos elegibles dentro del grupo familiar.',
              'La información de cada usuario permanece privada en su propia cuenta.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/google/FFFFFF',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Google'},
 {'id': 'ilovepdf',
  'name': 'iLovePDF Premium',
  'icon': 'simple-icons:ilovepdf',
  'accent': '#FF444F',
  'category': 'IA y productividad',
  'badge': 'PDF',
  'description': 'Herramientas premium para convertir, comprimir, editar, firmar y gestionar PDF.',
  'plans': [{'name': 'Perfil · 1 mes', 'price': 6},
            {'name': 'Perfil · 3 meses', 'price': 14},
            {'name': 'Cuenta completa privada · 1 año', 'price': 30}],
  'details': ['Acceso a herramientas premium de conversión, compresión, fusión, división y edición de PDF.',
              'Incluye OCR, firmas digitales, sincronización y créditos de IA según el plan.',
              'Disponible en web, móvil y escritorio.',
              'En cuentas compartidas, coordina el uso del código o acceso con el proveedor.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/ilovepdf/FF0000',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'iLovePDF'},
 {'id': 'leonardo',
  'name': 'Leonardo AI',
  'icon': 'simple-icons:leonardoai',
  'accent': '#8B5CF6',
  'category': 'IA y productividad',
  'badge': '8.5K',
  'description': 'Leonardo.Ai para generación de imágenes y contenido creativo con IA.',
  'plans': [{'name': '1 mes · 8,500 créditos', 'price': 18}],
  'details': ['8,500 créditos incluidos con suscripción privada de 1 mes.',
              'Acceso a PhotoReal, Alchemy, Prompt Magic y modelos exclusivos disponibles en el plan.',
              'Ideal para uso personal o reventa autorizada dentro de tus propios servicios.'],
  'notes': [],
  'logo_url': 'https://app.leonardo.ai/img/leonardo-by-canva.svg',
  'logo_class': 'brand-logo brand-logo-wide brand-logo-leonardo',
  'display_name': 'Leonardo.Ai'},
 {'id': 'lovable',
  'name': 'Lovable Lite',
  'icon': 'lucide:heart-handshake',
  'accent': '#FF4F87',
  'category': 'IA y productividad',
  'badge': '12M',
  'description': 'Acceso a Lovable Lite para construir aplicaciones y flujos de trabajo con IA.',
  'plans': [{'name': '12 meses · activación a correo', 'price': 60}],
  'details': ['5 créditos diarios, hasta 150 al mes.',
              '300 créditos de bono únicos.',
              'Dominios personalizados y opción de retirar el badge según el plan.'],
  'notes': []},
 {'id': 'notion',
  'name': 'Notion Business',
  'icon': 'simple-icons:notion',
  'accent': '#FFFFFF',
  'category': 'IA y productividad',
  'badge': 'BUSINESS',
  'description': 'Productividad, documentación y gestión de proyectos.',
  'plans': [{'name': 'Cuenta completa · 3 meses', 'price': 18}],
  'details': ['Espacios colaborativos, bases de datos, calendarios, notas y funciones de IA según disponibilidad.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/notion/FFFFFF',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Notion'},
 {'id': 'quillbot',
  'name': 'QuillBot Premium',
  'icon': 'simple-icons:quillbot',
  'accent': '#4DB6AC',
  'category': 'Educación',
  'badge': 'WRITE',
  'description': 'QuillBot Premium para paráfrasis, corrección, resúmenes y escritura asistida.',
  'plans': [{'name': '1 mes', 'price': 6}],
  'details': ['Paráfrasis premium, corrector, resúmenes y otras funciones del plan.'],
  'notes': [],
  'logo_url': 'https://quillbot.com/blog/wp-content/themes/blog-learneo-2024/img/Quillbot-logo.png',
  'logo_class': 'brand-logo brand-logo-wide brand-logo-quillbot',
  'display_name': 'QuillBot'},
 {'id': 'quizlet',
  'name': 'Quizlet Plus',
  'icon': 'simple-icons:quizlet',
  'accent': '#4255FF',
  'category': 'Educación',
  'badge': 'STUDY',
  'description': 'Herramientas premium para estudiar con flashcards y modos de aprendizaje.',
  'plans': [{'name': 'Cuenta privada · 1 mes', 'price': 25}],
  'details': ['Cuenta privada Quizlet Plus por 1 mes.',
              'Incluye experiencia sin anuncios, modo offline y herramientas premium de estudio según disponibilidad.',
              'Ideal para flashcards, pruebas, práctica y seguimiento de estudio.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/quizlet/4255FF',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Quizlet'},
 {'id': 'canva',
  'name': 'Canva Pro',
  'icon': 'simple-icons:canva',
  'accent': '#00C4CC',
  'category': 'Diseño',
  'badge': 'CANVA',
  'description': 'Diseño gráfico y creación de contenido con Canva Pro.',
  'plans': [{'name': '3 meses', 'price': 8},
            {'name': 'Otros periodos', 'price': None},
            {'name': 'Panel administrable · hasta 500 usuarios', 'price': 100}],
  'details': ['Panel Canva Pro compartido con capacidad de hasta 500 usuarios.',
              'Se asignan 3 administradores principales en el panel según coordinación.',
              'Puedes gestionar usuarios y revender accesos propios dentro de tu panel.',
              'La garantía indicada es de 6 meses o hasta completar los 500 usuarios.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/canva/00C4CC',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Canva'},
 {'id': 'capcut',
  'name': 'CapCut Pro',
  'icon': 'simple-icons:capcut',
  'accent': '#FFFFFF',
  'category': 'Diseño',
  'badge': 'VIDEO',
  'description': 'Edición de video premium sin marca de agua y con herramientas avanzadas.',
  'plans': [{'name': 'PC · 1 mes', 'price': 12}, {'name': 'Cuenta completa · 1 mes', 'price': 20}],
  'details': ['Edición premium sin marca de agua y con herramientas avanzadas.',
              'El plan para PC es compartido con 2 personas más, sin afectar el uso normal según lo indicado.',
              'La cuenta completa permite administración total por parte del comprador.'],
  'notes': [],
  'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Capcut-icon.svg',
  'logo_class': 'brand-logo brand-logo-square brand-logo-capcut',
  'display_name': 'CapCut'},
 {'id': 'chatgpt',
  'name': 'ChatGPT',
  'icon': 'simple-icons:openai',
  'accent': '#FFFFFF',
  'category': 'IA y productividad',
  'badge': 'AI',
  'description': 'Acceso o activación de planes ChatGPT únicamente cuando sea autorizado y conforme a las condiciones '
                 'del servicio.',
  'plans': [{'name': 'Plus · 1 mes', 'price': 15}, {'name': 'Go · 1 mes', 'price': 10}],
  'details': ['ChatGPT Plus de 1 mes y ChatGPT Go de 1 mes disponibles según el plan.',
              'Ideal para estudio, trabajo, redacción, programación y tareas con IA.'],
  'notes': ['No se ofrecen accesos obtenidos de cuentas ajenas ni credenciales sin autorización.'],
  'logo_url': 'https://cdn.simpleicons.org/openai/FFFFFF',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'ChatGPT'},
 {'id': 'office-e3',
  'name': 'Microsoft 365 E3',
  'icon': 'simple-icons:microsoft365',
  'accent': '#D83B01',
  'category': 'Productividad empresarial',
  'badge': 'MICROSOFT 365',
  'description': 'Suite empresarial de Microsoft con Word, Excel, PowerPoint, Outlook, OneDrive y herramientas de '
                 'administración.',
  'plans': [{'name': '1 año', 'price': 100}],
  'details': ['Microsoft 365 E3 es un plan empresarial de productividad y colaboración de Microsoft.',
              'Incluye aplicaciones de Microsoft 365 para web, móvil y escritorio, además de almacenamiento en la nube '
              'y funciones de administración y seguridad según el plan.',
              'La disponibilidad exacta de Teams, Windows Enterprise y otras funciones puede variar según la licencia '
              'que se entregue.'],
  'notes': [],
  'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Microsoft_365_%282022%29.svg',
  'logo_class': 'brand-logo brand-logo-square brand-logo-m365',
  'display_name': 'Microsoft 365 E3'},
 {'id': 'windows11',
  'name': 'Windows 11 Pro',
  'icon': 'simple-icons:windows11',
  'accent': '#0078D4',
  'category': 'Software',
  'badge': 'KEY',
  'description': 'Clave Retail para Windows 11 Pro.',
  'plans': [{'name': '1 PC · Retail Key', 'price': 25}],
  'details': ['Versión completa con licencia Retail para 1 PC.',
              'Entrega instantánea de clave y descarga.',
              'Garantía referencial de 180 días en la licencia entregada.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/windows11/0078D4',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Windows 11'},
 {'id': 'autodesk',
  'name': 'Autodesk',
  'icon': 'simple-icons:autodesk',
  'accent': '#0696D7',
  'category': 'Software',
  'badge': 'CAD',
  'description': 'Acceso a software Autodesk durante 12 meses según la licencia adquirida.',
  'plans': [{'name': '1 año · 1 PC', 'price': 20}],
  'details': ['Licencia por 12 meses para programas Autodesk según disponibilidad.',
              'Puede registrarse hasta en 2 equipos, con uso en uno a la vez.',
              'Si se cambia la contraseña de la cuenta y eso invalida la garantía, la cobertura puede perderse.'],
  'notes': [],
  'logo_url': 'https://cdn.simpleicons.org/autodesk/0696D7',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Autodesk'},
 {'id': 'office-plus',
  'name': 'Microsoft Office 365 Plus',
  'icon': 'simple-icons:microsoft',
  'accent': '#F25022',
  'category': 'Software',
  'badge': 'OFFICE',
  'description': 'Suite Microsoft Office 365 Plus.',
  'plans': [{'name': '1 año · no renovable', 'price': 30}],
  'details': ['Microsoft Office 365 Plus por 1 año, modalidad no renovable según el producto ofertado.',
              'Usa únicamente licencias oficiales y autorizadas.'],
  'notes': ['Usa únicamente licencias oficiales.'],
  'logo_url': 'https://cdn.simpleicons.org/microsoft/5E5E5E',
  'logo_class': 'brand-logo brand-logo-wide',
  'display_name': 'Microsoft'},
 {'id': 'sentinel',
  'name': 'Consulta de reporte crediticio',
  'icon': 'lucide:file-search-2',
  'accent': '#00D084',
  'category': 'Consultas',
  'badge': 'REPORTE',
  'description': 'Consulta de reporte crediticio únicamente para el propio titular o con autorización verificable.',
  'plans': [{'name': 'Consulta autorizada', 'price': 10}],
  'details': ['Puede incluir información reportada por entidades correspondientes.'],
  'notes': ['No se realizan consultas sobre terceros sin autorización.']}]

PAYMENT_METHODS = [{'id': 'yape',
  'name': 'Yape',
  'detail': 'Billetera móvil • Perú',
  'logo_url': 'https://www.yape.com.pe/_next/image?q=100&url=%2Fimages%2Fcomponents%2Fcomponent-25%2Flogo.png&w=256',
  'logo_fallback': 'img/payments/yape.svg',
  'logo_class': 'pay-logo-yape',
  'brand_color': '#7C238C'},
 {'id': 'plin',
  'name': 'Plin',
  'detail': 'Transferencias inmediatas • Perú',
  'logo_url': 'https://www.bbva.pe/content/dam/public-web/peru/images/promo-sliders/promo-plin.im1585949297034im.png?imwidth=960',
  'logo_fallback': 'img/payments/plin.svg',
  'logo_class': 'pay-logo-plin',
  'brand_color': '#00D3C7'},
 {'id': 'bcp',
  'name': 'BCP',
  'detail': 'Banco de Crédito del Perú',
  'logo_url': 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Logo-bcp-vector.svg',
  'logo_fallback': 'img/payments/bcp.svg',
  'logo_class': 'pay-logo-bcp',
  'brand_color': '#FF6B2C'},
 {'id': 'binance',
  'name': 'Binance',
  'detail': 'Cripto • pago coordinado por WhatsApp',
  'logo_url': 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Binance_logo.svg',
  'logo_fallback': 'img/payments/binance.svg',
  'logo_class': 'pay-logo-binance',
  'brand_color': '#F0B90B'}]

SOCIAL_PLATFORMS = [{'id': 'instagram',
  'name': 'Instagram',
  'icon': 'simple-icons:instagram',
  'accent': '#FF2D7A',
  'services': ['Seguidores', 'Likes', 'Comentarios', 'Compartidas', 'Vistas', 'Espectadores', 'Guardados']},
 {'id': 'facebook',
  'name': 'Facebook',
  'icon': 'simple-icons:facebook',
  'accent': '#1877F2',
  'services': ['Seguidores', 'Me gusta', 'Reacciones', 'Comentarios', 'Compartidas', 'Vistas', 'Espectadores']},
 {'id': 'tiktok',
  'name': 'TikTok',
  'icon': 'simple-icons:tiktok',
  'accent': '#25F4EE',
  'services': ['Seguidores', 'Likes', 'Comentarios', 'Compartidas', 'Vistas', 'Espectadores', 'Guardados']},
 {'id': 'youtube',
  'name': 'YouTube',
  'icon': 'simple-icons:youtube',
  'accent': '#FF0033',
  'services': ['Suscriptores', 'Likes', 'Comentarios', 'Compartidas', 'Vistas', 'Espectadores']},
 {'id': 'x',
  'name': 'X / Twitter',
  'icon': 'simple-icons:x',
  'accent': '#FFFFFF',
  'services': ['Seguidores', 'Likes', 'Respuestas', 'Reposts', 'Vistas']},
 {'id': 'threads',
  'name': 'Threads',
  'icon': 'simple-icons:threads',
  'accent': '#FFFFFF',
  'services': ['Seguidores', 'Likes', 'Respuestas', 'Reposts', 'Vistas']},
 {'id': 'telegram',
  'name': 'Telegram',
  'icon': 'simple-icons:telegram',
  'accent': '#26A5E4',
  'services': ['Miembros', 'Reacciones', 'Comentarios', 'Compartidas', 'Vistas']},
 {'id': 'linkedin',
  'name': 'LinkedIn',
  'icon': 'simple-icons:linkedin',
  'accent': '#0A66C2',
  'services': ['Seguidores', 'Reacciones', 'Comentarios', 'Compartidas', 'Vistas']},
 {'id': 'pinterest',
  'name': 'Pinterest',
  'icon': 'simple-icons:pinterest',
  'accent': '#E60023',
  'services': ['Seguidores', 'Guardados', 'Clics', 'Compartidas', 'Vistas']},
 {'id': 'twitch',
  'name': 'Twitch',
  'icon': 'simple-icons:twitch',
  'accent': '#9146FF',
  'services': ['Seguidores', 'Vistas', 'Espectadores', 'Interacciones', 'Chat']},
 {'id': 'discord',
  'name': 'Discord',
  'icon': 'simple-icons:discord',
  'accent': '#5865F2',
  'services': ['Miembros', 'Reacciones', 'Interacciones']},
 {'id': 'snapchat',
  'name': 'Snapchat',
  'icon': 'simple-icons:snapchat',
  'accent': '#FFFC00',
  'services': ['Seguidores', 'Vistas', 'Interacciones']},
 {'id': 'whatsapp',
  'name': 'WhatsApp',
  'icon': 'simple-icons:whatsapp',
  'accent': '#25D366',
  'services': ['Miembros de canal', 'Reacciones', 'Vistas']},
 {'id': 'reddit',
  'name': 'Reddit',
  'icon': 'simple-icons:reddit',
  'accent': '#FF4500',
  'services': ['Seguidores', 'Upvotes', 'Comentarios', 'Compartidas', 'Vistas']},
 {'id': 'kick',
  'name': 'Kick',
  'icon': 'simple-icons:kick',
  'accent': '#53FC18',
  'services': ['Seguidores', 'Vistas', 'Espectadores', 'Interacciones', 'Chat']}]
